##################################################
resolver: lts-13.15

          # ^ ghc-8.6.4

##################################################
packages:
- ./xxx-package-xxx

##################################################
# extra-deps:
#   -

##################################################