##################################################
resolver: lts-13.0
          # ^ (ghc-8.6.3)

##################################################
packages:
- .

##################################################
# extra-deps:
#   -

##################################################
