##################################################
resolver: lts-13.13

          # ^ ghc-8.6.4

##################################################
packages:
- .

##################################################
# extra-deps:
#   -

##################################################
