##################################################
resolver: lts-13.7
          # ^ (ghc-8.6.3)

##################################################
packages:
- ./skeletor/

##################################################
extra-deps:
- ../spiros/spiros/

#e.g.
# - git: git@github.com:yesodweb/wai
#   commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
#   subdirs:

##################################################