##################################################

resolver: lts-13.13
          # ^ (ghc-8.6.4)

#------------------------------------------------#

packages:

- ./skeletor/

#------------------------------------------------#

extra-deps:

- git:     https://github.com/sboosali/spiros.git
  commit:  0158ed5109c8b90c21347180aa84a891276ec007
  subdirs:
    - spiros

# - ../spiros/spiros/

##################################################



##################################################